LayerName:
  input_1:
    Precision: 
      result: ap_fixed<16,6>
    ReuseFactor: 144
    Trace: true  
  q_dense:
    Precision:
      bias: ap_fixed<12,7>
      weight: ap_fixed<12,7>
    ReuseFactor: 144
    Trace: true
  batch_normalization:
    Precision:
      scale: ap_fixed<16,6>
      bias: ap_fixed<16,6>
    ReuseFactor: 144
    Trace: true
  q_activation:
    Precision:
      result: ap_uint<6>
    ReuseFactor: 144
    Trace: true
  q_dense_1:
    Precision:
      bias: ap_fixed<12,7>
      weight: ap_fixed<12,7>
    ReuseFactor: 144
    Trace: true
  batch_normalization_1:
    Precision:
      scale: ap_fixed<16,6>
      bias: ap_fixed<16,6>
    ReuseFactor: 144
    Trace: true
  q_activation_1:
    Precision:
      result: ap_uint<6>
    ReuseFactor: 144
    Trace: true
  q_dense_2:
    Precision:
      bias: ap_fixed<12,7>
      weight: ap_fixed<12,7>
    ReuseFactor: 144
    Trace: true
  batch_normalization_2:
    Precision:
      scale: ap_fixed<16,6>
      bias: ap_fixed<16,6>
    ReuseFactor: 144
    Trace: true
  q_activation_2:
    Precision:
      result: ap_uint<6>
    ReuseFactor: 144
    Trace: true
  q_dense_3:
    Precision:
      bias: ap_fixed<12,7>
      weight: ap_fixed<12,7>
    ReuseFactor: 144
    Trace: true
  batch_normalization_3:
    Precision:
      scale: ap_fixed<16,6>
      bias: ap_fixed<16,6>
    ReuseFactor: 144
    Trace: true
  q_activation_3:
    Precision:
      result: ap_uint<6>
    ReuseFactor: 144
    Trace: true
  q_dense_4:
    Precision:
      bias: ap_fixed<12,7>
      weight: ap_fixed<12,7>
    ReuseFactor: 144
    Trace: true
  batch_normalization_4:
    Precision:
      scale: ap_fixed<16,6>
      bias: ap_fixed<16,6>
    ReuseFactor: 144
    Trace: true
  q_activation_4:
    Precision:
      result: ap_uint<6>
    ReuseFactor: 144
    Trace: true
  q_dense_5:
    Precision:
      bias: ap_fixed<12,7>
      weight: ap_fixed<12,7>
    ReuseFactor: 144
    Trace: true
Model:
  Strategy: Resource
  Precision: ap_fixed<16,6>
  ReuseFactor: 144
